### ISSUE TITLE
Exercice 5 Mistake (?)

### ISSUE THREAD

**Issue by baptiste60fps** [luruke/human-gpu#1]
Hello,
you done a great work here, these are very concrete exercices with a funny approach !

I think you made a mistake in you exercice **0005** : your _offset_ attribute is linked to an array of 3 value but his type is _vec2_ into your vertex shader. Maybe you should change either the length of buffer2 (to have X and Y offset) and of course the size of your attribute or the type of the offset attribute into your vertex shader.

Haste to resolve the next exercices !

**Comment by luruke** [comment]
Hello human id. @baptiste60fps !
good catch! 👍 

Fixed the typo and regenerated the pdf, thank you!
